### PR TITLE
Setup Local Development Environment

### PR DESCRIPTION
**Pull request by ngchisern**
* Simplify local development environment setup
* Use environment variable for JWT access secret in gateway
* Fix JWT verification inconsistency between gateway and user-service
* Update frontend configs

### CODE REVIEW

**Comment by ngchisern** [comment]
Set up the local environment:
* cd path/to/root
* run `docker-compose up --build -d`

The frontend and backend should be running at http://localhost and http://localhost:3001 respectively

Teardown:
* cd path/to/root
* run `docker-compose down`

**Comment by ngzhenteng** [comment]
Just to check, does this mean that locally we should use docker compose to test ah? thanks

**Comment by ngchisern** [comment]
> Just to check, does this mean that locally we should use docker compose to test ah? thanks



> Just to check, does this mean that locally we should use docker-compose to test ah? thanks

Yes!
I think it makes sense to use docker-compose for local development due to following reasons:
* Easy to set up and manage
* Allow hot-reload by creating volumes for each service

Let me know if you think otherwise.

**Comment by ngzhenteng** [comment]
awesome, thank you for setting it up

**Review by ngzhenteng — APPROVED** [review]
LGTM!

**Pull request merged**
