### PR TITLE
Modifications to UI

### PR DESCRIPTION
**Pull request by github-amanda**
1. Centralised Sign Up and Reset Password pages 
image

2. Modified layout of LoginPage to include an introduction to the application (please help to modify the introduction text :'))
image

3. Changed the font of the page headers and navbar. Might need some help to change the font of the MaterialUI components (e.g. Button)

4. Added button to view past attempts at the LandingPage and modified the buttons to make it slimmer
image

5. Added a 'Back' button for user to navigate from AttemptsPage to LandingPage
image

### CODE REVIEW

**Comment by ngchisern** [comment]
@ngzhenteng please help to modify the introduction text :')

**Comment by ngzhenteng** [comment]
LOL okay definitely, thanks

**Comment by github-amanda** [comment]
> LOL okay definitely, will do it later, please approve do not approve until then, thanks!

I've updated the introduction, but feel free to modify :') thanks

**Comment by ngzhenteng** [comment]
Looks great thank you!

**Review by ngzhenteng — APPROVED** [review]
LGTM thank you.

**Pull request merged**
